# Generated by Django 2.2 on 2019-06-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=8, unique=True, verbose_name='用户名')),
                ('userEmail', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('headimage', models.FileField(upload_to='tmp/', verbose_name='头像')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
