# Generated by Django 2.2.2 on 2019-06-22 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=10, verbose_name='任务编号')),
                ('task_name', models.CharField(max_length=20, verbose_name='任务名称')),
                ('inspect_line', models.CharField(max_length=20, verbose_name='巡检线路')),
                ('inspect_user', models.CharField(max_length=10, verbose_name='巡检员')),
                ('state', models.CharField(max_length=10, verbose_name='启用状态')),
                ('pole_beg', models.CharField(max_length=10, verbose_name='起始杆号')),
                ('pole_end', models.CharField(max_length=10, verbose_name='终止杆号')),
                ('df_username', models.CharField(max_length=20, verbose_name='下发人')),
                ('df_date', models.CharField(max_length=20, verbose_name='下发时间')),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
